<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>1.6.2.0</Version>
    <AssemblyName>bacneTPana</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />

    <PackageReference Include="OxyPlot.Wpf" Version="2.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\icons\toolicon.ico">
      <Link>icons\toolicon.ico</Link>
    </Resource>
    <Resource Include="..\..\images\toolicon.png">
      <Link>images\toolicon.png</Link>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\bacneTPana.Core\bacneTPana.Core.csproj" />
    <ProjectReference Include="..\bacneTPana.Models\bacneTPana.Models.csproj" />
    <ProjectReference Include="..\bacneTPana.DataAccess\bacneTPana.DataAccess.csproj" />
  </ItemGroup>

</Project>
